name: money4
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratM
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratB
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf